[package]
name = "rng-tsan-min-repro"
version = "0.1.0"
authors = ["David Kellum <dek-oss@gravitext.com>"]
edition = "2018"
description="Minimized reproduction of a thread sanitizer issue with getrandom 0.1.7"
license = "MIT/Apache-2.0"

[dependencies]
rand = "0.7"
